export const GEMS = [
  {
    id:     "diamond",
    name:   "Diamond",
    file:   "/models/diamond.glb",
    shadow: "/shadows/diamond-shadow.png",
    shader: {
      uIOR:                2.42,
      uDispersion:         0.044,
      uFresnelPower:       5.0,
      uGemColor:           [1.0, 1.0, 1.0],
      uAbsorptionColor:    [0.05, 0.02, 0.01],
      uAbsorptionStrength: 0.015,
      uReflectivity:       0.95,
      uTransmission:       0.95,
      uEnvIntensity:       1.2,
      uNormalSharpness:    0.08,
      uRGBBoost:           1.06,
    },
  },
  {
    id:     "ruby",
    name:   "Ruby",
    file:   "/models/ruby.glb",
    shadow: "/shadows/ruby-shadow.png",
    shader: {
      uIOR:                1.77,
      uDispersion:         0.013,
      uFresnelPower:       4.0,
      uGemColor:           [1.0, 0.05, 0.08],
      uAbsorptionColor:    [0.0, 0.85, 0.85],
      uAbsorptionStrength: 0.08,
      uReflectivity:       0.85,
      uTransmission:       0.80,
      uEnvIntensity:       1.0,
      uNormalSharpness:    0.06,
      uRGBBoost:           1.04,
    },
  },
  {
    id:     "emerald",
    name:   "Emerald",
    file:   "/models/emerald.glb",
    shadow: "/shadows/emerald-shadow.png",
    shader: {
      uIOR:                1.58,
      uDispersion:         0.014,
      uFresnelPower:       3.5,
      uGemColor:           [0.05, 0.85, 0.15],
      uAbsorptionColor:    [0.85, 0.0, 0.85],
      uAbsorptionStrength: 0.07,
      uReflectivity:       0.80,
      uTransmission:       0.75,
      uEnvIntensity:       0.95,
      uNormalSharpness:    0.07,
      uRGBBoost:           1.03,
    },
  },
  {
    id:     "sapphire",
    name:   "Sapphire",
    file:   "/models/sapphire.glb",
    shadow: "/shadows/sapphire-shadow.png",
    shader: {
      uIOR:                1.77,
      uDispersion:         0.018,
      uFresnelPower:       4.5,
      uGemColor:           [0.05, 0.12, 1.0],
      uAbsorptionColor:    [0.95, 0.75, 0.0],
      uAbsorptionStrength: 0.06,
      uReflectivity:       0.88,
      uTransmission:       0.82,
      uEnvIntensity:       1.1,
      uNormalSharpness:    0.07,
      uRGBBoost:           1.04,
    },
  },
  {
    id:     "topaz",
    name:   "Topaz",
    file:   "/models/topaz.glb",
    shadow: "/shadows/topaz-shadow.png",
    shader: {
      uIOR:                1.62,
      uDispersion:         0.014,
      uFresnelPower:       3.8,
      uGemColor:           [1.0, 0.55, 0.08],
      uAbsorptionColor:    [0.0, 0.45, 0.92],
      uAbsorptionStrength: 0.035,
      uReflectivity:       0.82,
      uTransmission:       0.88,
      uEnvIntensity:       1.05,
      uNormalSharpness:    0.06,
      uRGBBoost:           1.05,
    },
  },
];
