export const GEMS = [
  {
    id:     "diamond",
    name:   "Diamond",
    file:   "/models/diamond.glb",
    shadow: "/shadows/diamond-shadow.png",
    shader: {
      uIOR:                2.42,
      uDispersion:         0.18,
      uFresnelPower:       5.0,
      uGemColor:           [0.2, 0.6, 1.0],
      uAbsorptionColor:    [0.02, 0.01, 0.0],
      uAbsorptionStrength: 0.002,
      uReflectivity:       0.98,
      uTransmission:       1.0,
      uEnvIntensity:       2.0,
      uNormalSharpness:    0.4,
      uRGBBoost:           1.5,
    },
  },
  {
    id:     "ruby",
    name:   "Ruby",
    file:   "/models/ruby.glb",
    shadow: "/shadows/ruby-shadow.png",
    shader: {
      uIOR:                1.77,
      uDispersion:         0.1,
      uFresnelPower:       4.0,
      uGemColor:           [0.9, 0.02, 0.02],
      uAbsorptionColor:    [0.0, 0.9, 0.9],
      uAbsorptionStrength: 0.12,
      uReflectivity:       0.88,
      uTransmission:       1.06,
      uEnvIntensity:       1.3,
      uNormalSharpness:    0.25,
      uRGBBoost:           1.2,
    },
  },
  {
    id:     "emerald",
    name:   "Emerald",
    file:   "/models/emerald.glb",
    shadow: "/shadows/emerald-shadow.png",
    shader: {
      uIOR:                1.58,
      uDispersion:         0.08,
      uFresnelPower:       3.5,
      uGemColor:           [0.02, 0.8, 0.1],
      uAbsorptionColor:    [0.9, 0.0, 0.9],
      uAbsorptionStrength: 0.10,
      uReflectivity:       0.82,
      uTransmission:       1.0,
      uEnvIntensity:       1.2,
      uNormalSharpness:    0.25,
      uRGBBoost:           1.1,
    },
  },
  {
    id:     "sapphire",
    name:   "Sapphire",
    file:   "/models/sapphire.glb",
    shadow: "/shadows/sapphire-shadow.png",
    shader: {
      uIOR:                1.77,
      uDispersion:         0.10,
      uFresnelPower:       4.5,
      uGemColor:           [0.02, 0.08, 0.95],
      uAbsorptionColor:    [0.95, 0.8, 0.0],
      uAbsorptionStrength: 0.10,
      uReflectivity:       0.90,
      uTransmission:       1.0,
      uEnvIntensity:       1.3,
      uNormalSharpness:    0.25,
      uRGBBoost:           1.25,
    },
  },
  {
    id:     "topaz",
    name:   "Topaz",
    file:   "/models/topaz.glb",
    shadow: "/shadows/topaz-shadow.png",
    shader: {
      uIOR:                1.62,
      uDispersion:         0.12,
      uFresnelPower:       3.8,
      uGemColor:           [1.0, 0.5, 0.05],
      uAbsorptionColor:    [0.0, 0.5, 0.95],
      uAbsorptionStrength: 0.06,
      uReflectivity:       0.84,
      uTransmission:       1.0,
      uEnvIntensity:       1.2,
      uNormalSharpness:    0.25,
      uRGBBoost:           1.1,
    },
  },
];
