export const GEMS = [
  {
    id: "diamond",
    name: "Diamond",
    file: "/models/diamond.glb",
    shadow: "/shadows/diamond-shadow.png",
    shader: {
      uIOR: 2.42,
      // Pure white body color
      uGemColor: [0.96, 0.96, 1.0],
      uAbsorptionColor: [0.01, 0.01, 0.02],
      uAbsorptionStrength: 0.005,
      // Stronger dispersion split for richer rainbow facets
      uDispersion: 0.24,
      uFresnelPower: 5.0,
      uReflectivity: 0.98,
      uTransmission: 1.0,
      // Bright environment reflections
      uEnvIntensity: 2.2,
      uNormalSharpness: 0.25,
      // Boost dispersion split colors on facets since env map itself is colorless
      uRGBBoost: 1.8,
      // NEWLY ADDED: fully desaturate env map to avoid yellow-green/blue bleed
      uEnvSaturation: 0.0,
    },
  },
  {
    id: "ruby",
    name: "Ruby",
    file: "/models/ruby.glb",
    shadow: "/shadows/ruby-shadow.png",
    shader: {
      uIOR: 1.77,
      uGemColor: [0.75, 0.05, 0.06],
      uAbsorptionColor: [0.0, 0.85, 0.7],
      uAbsorptionStrength: 0.12,
      uDispersion: 0.018,
      uFresnelPower: 4.0,
      uReflectivity: 0.88,
      uTransmission: 1.06,
      uEnvIntensity: 1.8,
      uNormalSharpness: 0.25,
      uRGBBoost: 1.2,
      uEnvSaturation: 1.0,
    },
  },
  {
    id: "emerald",
    name: "Emerald",
    file: "/models/emerald.glb",
    shadow: "/shadows/emerald-shadow.png",
    shader: {
      uIOR: 1.58,
      uGemColor: [0.08, 0.65, 0.12],
      uAbsorptionColor: [0.7, 0.0, 0.7],
      uAbsorptionStrength: 0.10,
      uFresnelPower: 3.5,
      uReflectivity: 0.82,
      uTransmission: 1.0,
      uEnvIntensity: 1.6,
      uNormalSharpness: 0.35,
      uRGBBoost: 1.1,
      uEnvSaturation: 1.0,
    },
  },
  {
    id: "sapphire",
    name: "Sapphire",
    file: "/models/sapphire.glb",
    shadow: "/shadows/sapphire-shadow.png",
    shader: {
      uIOR: 1.77,
      uGemColor: [0.06, 0.14, 0.88],
      uAbsorptionColor: [0.8, 0.6, 0.0],
      uAbsorptionStrength: 0.08,
      uFresnelPower: 4.5,
      uReflectivity: 0.90,
      uTransmission: 1.0,
      uEnvIntensity: 1.8,
      uNormalSharpness: 0.25,
      uRGBBoost: 1.25,
      uEnvSaturation: 1.0,
    },
  },
  {
    id: "topaz",
    name: "Topaz",
    file: "/models/topaz.glb",
    shadow: "/shadows/topaz-shadow.png",
    shader: {
      uIOR: 1.62,
      uGemColor: [0.25, 0.75, 1.0],
      uAbsorptionColor: [0.6, 0.1, 0.0],
      uAbsorptionStrength: 0.06,
      uFresnelPower: 3.8,
      uReflectivity: 0.84,
      uTransmission: 1.0,
      uEnvIntensity: 1.6,
      uNormalSharpness: 0.25,
      uRGBBoost: 1.3,
      uEnvSaturation: 1.0,
    },
  },
];
